# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Publish images to Dockerhub from any branch Local

on:
  workflow_call:
    inputs:
      branch_name:
        description: Branch to build from
        required: true
        type: string
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'development'
        options:
          - development
          - qa
          - datamigration
          - staging
          - production
  workflow_dispatch:
    inputs:
      branch_name:
        default: tonga/deployment/dev
        required: true
        description: Branch to build from
  push:
    branches:
      - tonga/deployment/dev
jobs:
  base:
    environment: ${{ github.event.inputs.environment }}
    runs-on: [self-hosted, linux, "${{ github.event.inputs.environment }}"]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - uses: actions/checkout@v4
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set version and branch
        id: set-version-and-branch
        run: |
          export VERSION=`git log -1 --pretty=format:%h`
          echo "Pushing version $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # the event_name is the event that triggered the caller workflow
          # and not "workflow_call" like how it was supposed to be when
          # another workflow is calling this one

          if [ "${{ github.event_name }}" == 'push' ]; then
            BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          elif [ "${{ github.event_name }}" == 'pull_request' ]; then
            BRANCH=${{ github.event.pull_request.head.ref }}
          else
          BRANCH=${{ inputs.branch_name }}
          fi
          ESCAPED_BRANCH=$(echo $BRANCH | sed 's/[^a-zA-Z0-9_.-]/-/g')
          echo "from branch $BRANCH"
          echo "branch=$ESCAPED_BRANCH" >> $GITHUB_OUTPUT

      - name: Get list of services
        id: get-services
        run: |
          services=$(grep "^  [^ ]" docker-compose.yml | grep -v base| grep -v '#' | awk -F: '{print $1}' | sed -e 's/^ *//')
          services_json=$(echo $services | tr '\n' ',' | sed 's/,$//' | jq -R 'split(" ")' | tr -d '\n')
          # Set the list of service names as an output variable
          echo "services=$services_json" >> $GITHUB_OUTPUT
          echo "services=$services_json"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LOCALDOCKERUSER }}
          password: ${{ secrets.LOCALDOCKERPW }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          file: packages/Dockerfile.base
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_ORG2 }}/ocrvs-base:${{ steps.set-version-and-branch.outputs.version }}
            ${{ vars.DOCKER_ORG2 }}/ocrvs-base:${{ steps.set-version-and-branch.outputs.branch }}
          cache-from: type=registry,ref=${{ vars.DOCKER_ORG2 }}/ocrvs-base:${{ steps.set-version-and-branch.outputs.branch }}
          cache-to: type=inline

    outputs:
      services: ${{ steps.get-services.outputs.services }}
      version: ${{ steps.set-version-and-branch.outputs.version }}
      branch: ${{ steps.set-version-and-branch.outputs.branch }}

  build:
    needs: base
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.base.outputs.services) }}
    environment: ${{ github.event.inputs.environment }}
    runs-on: [self-hosted, linux, "${{ github.event.inputs.environment }}"]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: '${{ github.event.inputs.branch_name }}'

      - uses: actions/checkout@v4
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LOCALDOCKERUSER }}
          password: ${{ secrets.LOCALDOCKERPW }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: packages/${{ matrix.service }}/Dockerfile
          build-args: |
            VERSION=${{ needs.base.outputs.version }}
            BRANCH=${{ needs.base.outputs.branch }}
            DOCKER_ORG2ID=${{ vars.DOCKER_ORG2 }}
          push: true
          context: .
          tags: |
            ${{ vars.DOCKER_ORG2 }}/ocrvs-${{ matrix.service }}:${{ needs.base.outputs.version }}
            ${{ vars.DOCKER_ORG2 }}/ocrvs-${{ matrix.service }}:${{ needs.base.outputs.branch }}
          cache-from: type=registry,ref=${{ vars.DOCKER_ORG2 }}/ocrvs-${{ matrix.service }}:${{ needs.base.outputs.branch }}
          cache-to: type=inline
