name: Deploy Storybook to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'
          cache: 'npm'

      - name: Install dependencies
        run: yarn install
        working-directory: ./packages/components

      - name: Build Storybook
        run: yarn build-storybook
        working-directory: ./packages/components

      - name: Upload Storybook as artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook-static
          path: packages/components/build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Storybook Static Files
        uses: actions/download-artifact@v2
        with:
          name: storybook-static
          path: packages/components/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: packages/components/build
