name: Build and Deploy Storybook to Cloudflare Pages

on:
  push:
    branches:
      - master
      - release-v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'opencrvs/opencrvs-core'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
      # @TODO: when Yarn 2 is available
      #  run: yarn workspaces focus --production @opencrvs/components

      - name: Build components
        run: cd packages/components && yarn build

      - name: Build Storybook
        run: cd packages/components && yarn build-storybook

      - name: Deploy
        run: npx wrangler pages deploy ./packages/components/build --project-name opencrvs --branch ${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
