# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Build and Deploy Storybook to Cloudflare Pages

on:
  push:
    branches:
      - master
      - develop
      - release-v*
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/uikit')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'opencrvs/opencrvs-core'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
      # @TODO: when Yarn 2 is available
      #  run: yarn workspaces focus --production @opencrvs/components

      - name: Build components
        run: cd packages/components && yarn build

      - name: Build Storybook
        run: cd packages/components && yarn build-storybook

      - name: Deploy
        run: npx wrangler pages deploy ./packages/components/build --project-name opencrvs --branch ${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Comment deployment link on PR
        if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENT_BODY="Storybook deployed to: https://${{ github.ref_name }}.ui-kit.opencrvs.dev"
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.OLLIE_BOT_GITHUB_TOKEN }}
